# include:
 # - board: jaye_left
 # - board: jaye_right
 # - board: nrfmicro_13
  #  shield: settings_reset
#   shield: [jaye_left, jaye_right]
#  - board: [jaye_left, jaye_right]
#    name: ["Jaye"]

include:
  - board: jaye_left
  - board: jaye_right
  - shield: settings_reset
