manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/eddbrds/zmk-eddition
  projects:
    - name: zmk-eddition
      remote: zmkfirmware
      revision: main
      import: app/west.yml
  self:
    path: config
